services:
  neo4j:
    image: neo4j:5.23.0
    volumes:
      # Maps local directories to container paths for persistence:
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/staysovryn
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
